ALTER TABLE "ProductImage" ADD COLUMN "mediaUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "LandingVideo" ADD COLUMN "mediaUrl" TEXT NOT NULL DEFAULT '';

ALTER TABLE "ProductImage" ALTER COLUMN "mediaUrl" DROP DEFAULT;
ALTER TABLE "LandingVideo" ALTER COLUMN "mediaUrl" DROP DEFAULT;
